name: travenx_loitafoundation
description: Travenx
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # load images from internet
  cached_network_image: ^3.2.0

  # get vector file as image
  flutter_svg: ^1.0.3

  # get readmore button package
  readmore: ^2.1.0

  # ListView load more
  pull_to_refresh: ^2.0.0

  # state management package
  provider: ^6.0.2

  # Firebase Authentication
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11

  # Flutter Facebook Authentication
  flutter_facebook_auth: ^4.1.2

  # Flutter Google Sign In
  google_sign_in: ^5.2.4

  # Flutter Secure Storage
  flutter_secure_storage: ^5.0.2

  # Loading Screen
  flutter_spinkit: ^5.1.0
  animated_text_kit: ^4.2.1

  # Firebase Cloud Firestore
  cloud_firestore: ^3.1.10

  # Firebase Storage
  firebase_storage: ^10.2.14

  #rFlutter Alert
  rflutter_alert: ^2.0.4

  # GeoLocator
  geolocator: ^8.2.0

  # HTTP request
  http: ^0.13.4

  # Image Picker
  image_picker: ^0.8.4+11

  # Internet Connection Checker
  internet_connection_checker: ^0.0.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/home_screen/
    - assets/images/home_screen/sub/
    - assets/images/profile_screen/
    - assets/icons/profile_screen/
    - assets/icons/
    - assets/icons/home_screen/
    - assets/icons/home_screen/sub/

  fonts:
    - family: Nokora
      fonts:
        - asset: fonts/Nokora-Regular.ttf
    - family: CustomOutlinedIcons
      fonts:
        - asset: fonts/Custom-Oulined-Icons.ttf
    - family: CustomFilledIcons
      fonts:
        - asset: fonts/Custom-Filled-Icons.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf